---
- name: Build ZFS, enable nfs-kernel-server, create encrypted dataset, export it
  hosts: all
  become: true
  pre_tasks:
    - shell: apt-get install -y linux-headers-$(uname -r) build-essential autoconf libtool gawk alien fakeroot zlib1g-dev uuid-dev libattr1-dev libblkid-dev libselinux-dev libudev-dev libssl-dev parted lsscsi ksh automake
    - shell: git clone {{item}}
      with_items:
        - https://github.com/zfsonlinux/spl
        - https://github.com/zfsonlinux/zfs
      ignore_errors: true
    - shell: cd spl; git checkout master; ./autogen.sh; ./configure; make; make install
      args:
        creates: /usr/local/src/spl-0.7.0
    - shell: cd zfs; git checkout master; ./autogen.sh; ./configure --prefix=/usr; make; make install
      args:
        creates: /usr/sbin/zpool
    - shell: "modprobe -r {{item}}"
      with_items: 
        - splat
        - zavl
        - zcommon
        - zunicode
        - znvpair
        - icp
        - zlua
        - spl
        - zfs
      ignore_errors: true
    - shell: "cd /lib/modules/$(uname -r)/extra; insmod {{item}}"
      with_items: 
        - unicode/zunicode.ko 
        - spl/spl.ko
        - nvpair/znvpair.ko 
        - zcommon/zcommon.ko 
        - lua/zlua.ko
        - icp/icp.ko 
        - avl/zavl.ko 
        - zfs/zfs.ko
      ignore_errors: true
  roles:
    - ansible-zfs
  post_tasks:
    - shell: zpool create tank /dev/vdb -f
      args:
        creates: /tank
    - shell: zpool set feature@encryption=enabled tank
    - shell: "echo {{zfs_key}} > {{zfs_key_location}}"
    - shell: "zfs create -o encryption=aes-128-gcm -o keyformat=hex -o keylocation=file://{{zfs_key_location}} -o atime=off -o logbias=latency -o mountpoint=/tank/nfs -o sharenfs=rw=@{{openstack_project_subnet}} -o sync=always tank/nfs"
      args:
        creates: /tank/nfs
    - lineinfile:
        path: /etc/exports
        line: "/tank/nfs {{openstack_project_subnet}}(rw,sync)"
    - shell: exportfs -a
